name: Sawab
description: Sawab, developed by Anwar O. telegram@google45

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-204.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # cupertino_icons: ^1.0.2
  # win32: ^4.1.2
  curved_labeled_navigation_bar: ^2.0.2
  like_button: ^2.0.5
  flutter_bloc: ^8.1.2
  provider: ^6.0.5
  sqflite: ^2.2.4+1
  fl_chart: ^0.61.0
  url_launcher: ^6.1.10
  syncfusion_flutter_pdfviewer: ^21.1.39
  flutter_svg: ^2.0.4
  # capture screenshot:
  # screenshot: ^1.3.0
  # finding commonly used locations on the filesystem
  path_provider: ^2.0.14
  share_plus: ^6.3.2
  screenshot: ^1.3.0
   #slide_to_act: any    //import 'package:slide_to_act/slide_to_act.dart';
  #path_provider: ^2.0.12
  

#   curved_labeled_navigation_bar - for main bottom navigation bar
#                         sqflite - for local save data
#                   path_provider - for local save data

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/Belyi_Minaret.svg
    - lib/assets/images/Belyi_Minaret.png
    - lib/assets/images/LoveForAllHatredForNone.jpg
    - lib/assets/pdf/Namaz-3.pdf
    - lib/assets/pdf/Ramadan.pdf

  fonts:
  - family: Comfortaa
    fonts:
      - asset: lib/fonts/Comfortaa/static/Comfortaa-Light.ttf
        weight: 300
      - asset: lib/fonts/Comfortaa/static/Comfortaa-Regular.ttf
        weight: 400
      - asset: lib/fonts/Comfortaa/static/Comfortaa-Medium.ttf
        weight: 500
      - asset: lib/fonts/Comfortaa/static/Comfortaa-SemiBold.ttf
        weight: 600
      - asset: lib/fonts/Comfortaa/static/Comfortaa-Bold.ttf
        weight: 700

# SAMPLE Fonts
#  fonts:
#  - family: Comfortaa
#    fonts:
#      - asset: lib/fonts/Comfortaa/static/Comfortaa-Light.ttf
#        weight: 300
